### ISSUE TITLE
利用 GitHub Pages 和 Hexo 搭建个人博客

### ISSUE THREAD

**Issue by zhnoah** [zhnoah/blog#2]
## Step 0 —— 环境及前提条件

* 1.Github 账号

* 2.Node.js
```
node -v // v7.10.1
npm -v  // 4.6.1
```

* 3.Git
```
git --version // git version 2.10.2.windows.1
```

## Step 1 —— 新建 Github 仓库

* 登录 Github 后点击 New repository 菜单

* 仓库名称使用 *xxx*.github.io 格式

* 根据需求填写仓库描述及是否创建 README 文件

* 创建成功后，即可浏览 [xxx.github.io](https://xxx.github.io/) 页面

## Step 2 —— 创建 Hexo 项目

* 安装 hexo 命令行工具
```
npm i -g hexo-cli
```

* 验证是否安装成功
```
hexo -v // hexo-cli: 1.0.4
```

* 初始化 hexo 项目
```
hexo init blog
```

* 待完成后，安装 *hexo-deployer-git* 包为部署做准备
```
cd blog && npm i hexo-deployer-git --save
```

* 启动服务
```
hexo s  // 浏览器中打开 localhost:4000 查看
```

## Step 3 —— 更换主题[可选]

* 在 [Hexo theme](https://hexo.io/themes/) 页面选择自己喜欢的主题，推荐 [NexT](https://github.com/iissnan/hexo-theme-next)

* 执行命令下载主题
```
// 这里以 NexT 为例
// 成功下载后，可在项目 themes 文件夹查看
git clone https://github.com/iissnan/hexo-theme-next themes/next
```

* 更改配置
```
  // 编辑项目目录下的 _config.yml 文件中 theme 项
  # theme: landscape
  theme: next
```

* 重启服务查看更改效果

## Step 4 —— 部署

* 配置 Hexo Configuration
```
// 打开 _config.yml 文件，依次更改所需的项，主要包括
title: xxx's Notes
author: xxx
url: https://xxx.github.io
deploy:
  type: git
  repo: git@github.com:xxx/xxx.github.io.git
  branch: master
```

* 配置 Git 信息
```
git config --global user.name "xxx"
git config --global user.email "xxx@mail.com"
```

* 生成 SSH
```
// 注意使用 Git Bash
$ ssh-keygen -t rsa -C "xxx@mail.com"
```

* 将生成的 SSH Key 添加到 Github 账号
```
// 在 C:\Users\Administrator\.ssh 目录下找到 id_rsa.pub 文件
// 使用记事本打开该文件，复制全部内容
// 到 Github 网站，个人 Settings 菜单中，左侧找到 SSH and GPG keys 项
// 点击 New SSH key 按钮，Title 中随意填入一个名字，如 blog
// Key 中粘贴入复制的内容，点击添加按钮
```

* 部署
```
// 部署
hexo d
// or
// 在部署前生成静态文件
hexo d -g
```
